repos:
  - repo: local
    hooks:
      - id: ruff check
        name: ruff check
        entry: poetry run ruff check --extend-select I --fix
        language: system
        types: [python]

      - id: ruff format
        name: ruff format
        entry: poetry run ruff format
        language: system
        types: [python]

      - id: mdformat
        name: mdformat
        entry: poetry run mdformat --wrap 88
        language: system
        types: [markdown]
